### ISSUE TITLE
Build fails: ValueError: Could not find: linalg_nleq2.f ($PYNLEQ2_NLEQ2_ROOT_URL not set)

### ISSUE THREAD

**Issue by yurivict** [bjodah/pynleq2#5]
setup.py explicitly lists files like linalg_nleq2.f as required and they are missing from the repository posted to PYPI.

All files required for build should be present in the repository.
Downloads aren't allowed during package build.

Version: 0.1.0
FreeBSD 14.1

**Comment by bjodah** [comment]
NLEQ2 license does not permit redistribution.
